### PR TITLE
Fix time_daemon denies

### PR DESCRIPTION
**Pull request by ElXreno**
```
05-19 14:02:50.912 27585 27585 W time_daemon: type=1400 audit(0.0:23061): avc: denied { dac_override } for capability=1 scontext=u:r:time_daemon:s0 tcontext=u:r:time_daemon:s0 tclass=capability permissive=0
05-19 14:02:50.912 27585 27585 W time_daemon: type=1400 audit(0.0:23062): avc: denied { dac_read_search } for capability=2 scontext=u:r:time_daemon:s0 tcontext=u:r:time_daemon:s0 tclass=capability permissive=0
```

### CODE REVIEW

**Comment by Sap1k** [comment]
Neverallows are not allowed, and it would not even fix it in the first place
Recommend to close
The true fix is adding this line into sepolicy/vendor/time_daemon.te
allow time_daemon time_daemon:capability { dac_override dac_read_search };

**Comment by ElXreno** [comment]
@Sap1k it gives build sepolicy error and only one fix what I found is that.

**Comment by Sap1k** [comment]
Nope, my EvoX sepolicy has it that way and it works perfectly fine :)

**Comment by ElXreno** [comment]
@Sap1k EvoX != Pixel Experience.
At least this build error exists in LineageOS. Maybe it really will work on PE.

**Comment by Sap1k** [comment]
Yep I know :D
But SEPolicy is very similar for both Evo and PE
You should try on PE, as your fix might NOT work there
And you had to include a SELINUX_INGNORE_NEVERALLOWS=true in order for checkpolicy to pass, which is not in any way a desirable thing

**Comment by ElXreno** [comment]
Currently I don't have much time for android building, so I can't test this with PE.
But I can override my PR if your solution really will work.

**Comment by Sap1k** [comment]
Either way, I think lmc will include this himself, so yeah

**Comment by ElXreno** [comment]
@Sap1k I hope, because currently `time_daemon` crashes every 2-3 seconds and restarts. It's not a good.

**Comment by ElXreno** [comment]
> And you had to include a SELINUX_INGNORE_NEVERALLOWS=true

I never do that and all works for me...
Also I discover neverallows in LineageOS sepolicy which disallows `dac_override & dac_read_search`, that why I use this.

**Pull request merged**
